name: Example
on: [push]
jobs:
  
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Run tools
        uses: uv run pre-commit run -a
               
      - name: Run tests
        uses: uv run python -m unittest
